### ISSUE TITLE
Package url referring to wrong repo

### ISSUE THREAD

**Issue by jimwheaton** [Outblock/fcl-swift#1]
The package `url` in [Package.swift](https://github.com/Outblock/fcl-swift/blob/main/Package.swift#L19) is referring to the wrong repo, which makes adding the package to a Swift app confusing. The README also [refers to `zed-io`](https://github.com/Outblock/fcl-swift/blob/main/README.md?plain=1#L28).

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/1443842/153963084-db638e00-2591-4bd1-8352-0b86082cea52.png">

**Comment by lmcmz** [comment]
Yeah, you are right. Let me update this.
I was moving this repo from old one in a hurry. 😹

**Comment by lmcmz** [comment]
Updated: [this commit](https://github.com/Outblock/fcl-swift/commit/88e4217fe653577e3007a43eb4f684700d75890e)

**Comment by jimwheaton** [comment]
Thank you!
