### ISSUE TITLE
Fails to open the new Flow Reference Wallet app

### ISSUE THREAD

**Issue by ErichWood** [Outblock/fcl-swift#28]
The Flow wallet app was updated and has a new app ID. This library tries to connect using the old app, which is no longer available.

**Comment by lmcmz** [comment]
hey @ErichWood , thanks for reporting. 

We have updated the wallet info, could you please try with the new version `0.1.3` ?

**Comment by ErichWood** [comment]
@lmcmz Yes it is fixed thanks!
